development:
  adapter: mysql2
  database: rails_event_logger_development
  username: root
  password:
  encoding: utf8

production:
  adapter: mysql2
  database: rails_event_logger_production
  username: root
  password:
  encoding: utf8

test:
  adapter: mysql2
  database: rails_event_logger_test
  username: root
  password:
  encoding: utf8
